// <auto-generated />
using System;
using Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240529142610_Move TaskAssigned to DTO")]
    partial class MoveTaskAssignedtoDTO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Models.ListCategoryDTO", b =>
                {
                    b.Property<byte>("ID")
                        .HasColumnType("smallint");

                    b.Property<short?>("Permissionextid")
                        .HasColumnType("smallint");

                    b.HasKey("ID")
                        .HasName("listcategory_pkey");

                    b.ToTable("ListCategories");
                });

            modelBuilder.Entity("Application.Models.RolePermissionExt", b =>
                {
                    b.Property<short>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("TenantID"));

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<short?>("Permissionextid")
                        .HasColumnType("smallint");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("TenantID")
                        .HasName("rolepermissionext_pkey");

                    b.ToTable("rolepermissionext", "adm");
                });

            modelBuilder.Entity("Application.Models.TaskDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ApprovalWith")
                        .HasColumnType("integer");

                    b.Property<int>("EscalatedTo")
                        .HasColumnType("integer");

                    b.HasKey("ID")
                        .HasName("task_pkey");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Application.Models.TaskOnlineAssigned", b =>
                {
                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("integer");

                    b.HasKey("TenantID", "TaskID")
                        .HasName("taskonlineassigned_pkey");

                    b.ToTable("TasksOnlineAssigned");
                });

            modelBuilder.Entity("Application.Models.TaskResponsibleUserDTO", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("TaskID")
                        .HasName("taskresponcibleuser_pkey");

                    b.ToTable("TaskResponsibleUsers");
                });

            modelBuilder.Entity("Application.Models.TaskUserCacheDTO", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskID"));

                    b.Property<byte>("TaskListCategoryID")
                        .HasColumnType("smallint");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("TaskID")
                        .HasName("taskusercache_pkey");

                    b.ToTable("TaskUserCacheDTO");
                });

            modelBuilder.Entity("Application.Models.UserDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.HasKey("ID")
                        .HasName("user_pkey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Application.Models.UserDistrict", b =>
                {
                    b.Property<int>("DistrictID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("DistrictID", "UserID")
                        .HasName("userdistrict_pkey");

                    b.ToTable("userdistrict", "adm");
                });

            modelBuilder.Entity("Application.Models.UserRole", b =>
                {
                    b.Property<short>("TenantID")
                        .HasColumnType("smallint");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("TenantID", "UserID")
                        .HasName("userrole_pkey");

                    b.ToTable("userrole", "adm");
                });

            modelBuilder.Entity("Application.Models.UserTaskListCategoryDTO", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<byte>("TaskListCategoryID")
                        .HasColumnType("smallint");

                    b.HasKey("UserID")
                        .HasName("usertasklistcategory_pkey");

                    b.ToTable("UserTasksListCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
